name: UV Publish to PyPI (Test)

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Wait for Tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests (3.13t)"
          wait-interval: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests (3.13)"
          wait-interval: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests (3.12)"
          wait-interval: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests (3.11)"
          wait-interval: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests (3.10)"
          wait-interval: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install latest uv
        uses: astral-sh/setup-uv@v6

      - name: Build the package with uv
        run: uv build

      - name: Verify the package built in dist matches the pushed tag
        run: |
          pushed_tag=${GITHUB_REF_NAME}
          package_version=$(uv version --short)
          if [ "$pushed_tag" != "$package_version" ]; then
            echo "Error: Pushed tag $pushed_tag does not match package version $package_version."
            exit 1
          fi
          echo "Verification successful: Pushed tag $pushed_tag matches package version $package_version."

      - name: Publish to PyPI (Test)
        run: uv publish --index testpypi --trusted-publishing always

      - name: Publish to PyPI (Prod)
        run: uv publish --trusted-publishing always
