name: UV Build Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-uv-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.13t"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install latest uv
        uses: astral-sh/setup-uv@v6

      - name: Build the package with uv
        run: |
          uv build

      - name: Test that executing the package --help works
        run: |
          uvx --from dist/pycti_mcp-*.tar.gz pycti-mcp --help

      - name: Test that executing the package yields a list of tools
        run: |
          (
            echo '{"jsonrpc":"2.0","method":"initialize","id":1,"params":{"protocol_version": "2025-03-26", "capabilities": {"roots": {"listChanged": true}, "sampling"{}}, "clientInfo": {"name": "TestUVClient", "version": "1.0.0"}}}' \
              && sleep 10 \
              && echo '{"jsonrpc":"2.0","method":"tools/list","id":1}' \
          ) | stdbuf -oL uvx --from dist/pycti_mcp-*.tar.gz pycti-mcp \
            | jq
